require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Max: 275

Metrics/MethodLength:
  CountAsOne: ['hash', 'array', 'heredoc']
  Max: 25

Naming/VariableNumber:
  CheckSymbols: false
  EnforcedStyle: snake_case

Style/Documentation:
  Enabled: false

Rails/WhereEquals:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/**/*

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
