AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*
Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context', 'it']
Metrics/MethodLength:
  CountAsOne: ['hash', 'array']
Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*
