AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/**/*
    - spec/**/*
Metrics/BlockLength:
  IgnoredMethods: ['namespace']
Metrics/MethodLength:
  CountAsOne: ['hash', 'array', 'heredoc']
Layout/LineLength:
  Max: 140