AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - spec/**/*
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Max: 250
Metrics/MethodLength:
  CountAsOne: ['hash', 'array', 'heredoc']
  Max: 15
Layout/LineLength:
  Max: 140
Style/Documentation:
  Enabled: false
