require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - spec/**/*
Layout/LineLength:
  Max: 140
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
Metrics/ClassLength:
  Max: 275
Metrics/MethodLength:
  CountAsOne: ['hash', 'array', 'heredoc']
  Max: 25
Naming/VariableNumber:
  CheckSymbols: false
  EnforcedStyle: snake_case
Style/Documentation:
  Enabled: false
