version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19

  pre_build:
    commands:
      - docker login -u squeakyai -p "${SQUEAKY_DOCKER_PASSWORD}"
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build --platform linux/arm64 -t api:latest .
      - docker tag api:latest "${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/api:latest"
      - docker push "${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/api:latest"

  post_build:
    commands:
      - aws ecs update-service --cluster squeaky-prod --service api --force-new-deployment
      - aws ecs update-service --cluster squeaky-prod --service api_worker --force-new-deployment
      - aws ecs wait services-stable --cluster squeaky-prod --services api api_worker

