version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18

  pre_build:
    commands:
      - docker login -u squeakyai -p "${SQUEAKY_DOCKER_PASSWORD}"
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - docker build -t api:latest .
      - docker tag api:latest "${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/api:latest"
      - docker push "${AWS_ACCOUNT_ID}.dkr.ecr.eu-west-1.amazonaws.com/api:latest"

  post_build:
    commands:
      - aws ecs update-service --cluster squeaky --service "squeaky-api" --force-new-deployment
      - aws ecs wait services-stable --cluster squeaky --services "squeaky-api"
