version: '2.0'

services:
  web:
    build: .
    ports:
      - 4000:4000
    environment:
      RAILS_ENV: development
      POSTGRES_HOST: postgres
      REDIS_URL: redis://redis:6379/1
    depends_on:
      - postgres
      - redis
    volumes:
      - '.:/app'
      - '~/.aws:/root/.aws'

  postgres:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'squeaky_development'
      POSTGRES_USER: 'squeaky'
      POSTGRES_PASSWORD: 'squeaky'
    volumes:
      - 'tmp/postgres-data:/var/lib/postgresql/data'

  redis:
    image: redis:5-alpine
    volumes:
      - 'tmp/redis-data:/data'
