# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ApplicationMailer`.
# Please instead update this file by running `bin/tapioca dsl ApplicationMailer`.

class ApplicationMailer
  include GeneratedUrlHelpersModule

  class << self
    sig { params(path: T.untyped).returns(::ActionMailer::MessageDelivery) }
    def squeaky_url(path = T.unsafe(nil)); end
  end
end
