# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `DataExportJob`.
# Please instead update this file by running `bin/tapioca dsl DataExportJob`.

class DataExportJob
  class << self
    sig { params(data_export_id: T.untyped).returns(T.any(DataExportJob, FalseClass)) }
    def perform_later(data_export_id); end

    sig { params(data_export_id: T.untyped).returns(T.untyped) }
    def perform_now(data_export_id); end
  end
end
