# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `EventTrackingJob`.
# Please instead update this file by running `bin/tapioca dsl EventTrackingJob`.

class EventTrackingJob
  class << self
    sig { params(args: T.untyped).returns(T.any(EventTrackingJob, FalseClass)) }
    def perform_later(*args); end

    sig { params(args: T.untyped).returns(T.untyped) }
    def perform_now(*args); end
  end
end
