# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `NewFeedbackJob`.
# Please instead update this file by running `bin/tapioca dsl NewFeedbackJob`.

class NewFeedbackJob
  class << self
    sig { params(_args: T.untyped).returns(T.any(NewFeedbackJob, FalseClass)) }
    def perform_later(*_args); end

    sig { params(_args: T.untyped).returns(T.untyped) }
    def perform_now(*_args); end
  end
end
