# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `RecordingDeleteJob`.
# Please instead update this file by running `bin/tapioca dsl RecordingDeleteJob`.

class RecordingDeleteJob
  class << self
    sig { params(recording_ids: T.untyped).returns(T.any(RecordingDeleteJob, FalseClass)) }
    def perform_later(recording_ids); end

    sig { params(recording_ids: T.untyped).returns(T.untyped) }
    def perform_now(recording_ids); end
  end
end
