# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `UserCleanupJob`.
# Please instead update this file by running `bin/tapioca dsl UserCleanupJob`.

class UserCleanupJob
  class << self
    sig { params(_args: T.untyped).returns(T.any(UserCleanupJob, FalseClass)) }
    def perform_later(*_args); end

    sig { params(_args: T.untyped).returns(T.untyped) }
    def perform_now(*_args); end
  end
end
