# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `WeeklyReviewEmailsJob`.
# Please instead update this file by running `bin/tapioca dsl WeeklyReviewEmailsJob`.

class WeeklyReviewEmailsJob
  class << self
    sig { params(args: T.untyped).returns(T.any(WeeklyReviewEmailsJob, FalseClass)) }
    def perform_later(*args); end

    sig { params(args: T.untyped).returns(T.untyped) }
    def perform_now(*args); end
  end
end
