# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Events::RuleInput`.
# Please instead update this file by running `bin/tapioca dsl Types::Events::RuleInput`.

class Types::Events::RuleInput
  sig { returns(::String) }
  def condition; end

  sig { returns(T.nilable(::String)) }
  def field; end

  sig { returns(::String) }
  def matcher; end

  sig { returns(::String) }
  def value; end
end
