default: &default
  ar: 'Arabic'
  ar_ae: 'Arabic (UAE)'
  ar_bh: 'Arabic (BH)'
  ar_dz: 'Arabic (DZ)'
  ar_eg: 'Arabic (EG)'
  ar_iq: 'Arabic (IQ)'
  ar_jo: 'Arabic (JO)'
  ar_kw: 'Arabic (KW)'
  ar_lb: 'Arabic (LB)'
  ar_ly: 'Arabic (LY)'
  ar_ma: 'Arabic (MA)'
  ar_om: 'Arabic (OM)'
  ar_qa: 'Arabic (QA)'
  ar_sa: 'Arabic (SA)'
  ar_sd: 'Arabic (SD)'
  ar_sy: 'Arabic (SY)'
  ar_tn: 'Arabic (TN)'
  ar_ye: 'Arabic (YE)'
  be: 'Belarusian'
  be_by: 'Belarusian (BY)'
  bg: 'Bulgarian'
  bg_bg: 'Bulgarian (BG)'
  bn: 'Bengali'
  bn_bd: 'Bengali (BD)'
  bn_in: 'Bengali (IN)'
  ca: 'Catalan'
  ca_es: 'Catalan (ES)'
  cs: 'Czech'
  cs_cz: 'Czech (CZ)'
  da: 'Danish'
  da_dk: 'Danish (DK)'
  de: 'German'
  de_at: 'German (AT)'
  de_ch: 'German (CH)'
  de_de: 'German (DE)'
  de_lu: 'German (LU)'
  el: 'Greek'
  el_cy: 'Greek (CY)'
  el_gr: 'Greek (GR)'
  en: 'English'
  en_au: 'English (AU)'
  en_ca: 'English (CA)'
  en_gb: 'English (GB)'
  en_ie: 'English (IE)'
  en_in: 'English (IN)'
  en_mt: 'English (MT)'
  en_nz: 'English (NZ)'
  en_ph: 'English (PH)'
  en_sg: 'English (SG)'
  en_us: 'English (US)'
  en_za: 'English (SA)'
  es: 'Spanish'
  es_ar: 'Spanish (AR)'
  es_bo: 'Spanish (BO)'
  es_cl: 'Spanish (CL)'
  es_co: 'Spanish (CO)'
  es_cr: 'Spanish (CR)'
  es_do: 'Spanish (DO)'
  es_ec: 'Spanish (EC)'
  es_es: 'Spanish (ES)'
  es_gt: 'Spanish (GT)'
  es_hn: 'Spanish (HN)'
  es_mx: 'Spanish (MX)'
  es_ni: 'Spanish (NI)'
  es_pa: 'Spanish (PA)'
  es_pe: 'Spanish (PE)'
  es_pr: 'Spanish (PR)'
  es_py: 'Spanish (PY)'
  es_sv: 'Spanish (SV)'
  es_us: 'Spanish (US)'
  es_uy: 'Spanish (UY)'
  es_ve: 'Spanish (VE)'
  et: 'Estonian'
  et_ee: 'Estonian (EE)'
  fi: 'Finnish'
  fi_fi: 'Finnish (FI)'
  fr: 'French'
  fr_be: 'French (BE)'
  fr_ca: 'French (CA)'
  fr_ch: 'French (CH)'
  fr_fr: 'French (FR)'
  fr_lu: 'French (LU)'
  ga: 'Irish'
  ga_ie: 'Irish (IE)'
  hi_in: 'Hindi (IN)'
  hr: 'Croatian'
  hr_hr: 'Croatian (HR)'
  hu: 'Hungarian'
  hu_hu: 'Hungarian (HU)'
  in: 'Indonesian'
  in_id: 'Indonesian (ID)'
  is: 'Icelandic'
  is_is: 'Icelandic (IS)'
  it: 'Italian'
  it_ch: 'Italian (CH)'
  it_it: 'Italian (IT)'
  iw: 'Hebrew'
  iw_il: 'Hebrew (IL)'
  ja: 'Japanese'
  ja_jp: 'Japanese (JP)'
  ko: 'Korean'
  ko_kr: 'Korean (KR)'
  lt: 'Lithuanian'
  lt_lt: 'Lithuanian (LV)'
  lv: 'Latvian'
  lv_lv: 'Latvian (LV)'
  mk: 'Macedonian'
  mk_mk: 'Macedonian (MK)'
  ms: 'Malay'
  ms_my: 'Malay (MY)'
  mt: 'Maltese'
  mt_mt: 'Maltese (MT)'
  nl: 'Dutch'
  nl_be: 'Dutch (BE)'
  nl_nl: 'Dutch (NL)'
  no: 'Norwegian'
  no_no: 'Norwegian (NO)'
  pl: 'Polish'
  pl_pl: 'Polish (PL)'
  pt: 'Portuguese'
  pt_br: 'Portuguese (BR)'
  pt_pt: 'Portuguese (PT)'
  ro: 'Romanian'
  ro_ro: 'Romanian (RO)'
  ru: 'Russian'
  ru_ru: 'Russian (RU)'
  sk: 'Slovak'
  sk_sk: 'Slovak (SK)'
  sl: 'Slovenian'
  sl_si: 'Slovenian (SI)'
  sq: 'Albanian'
  sq_al: 'Albanian (AL)'
  sr: 'Serbian'
  sr_ba: 'Serbian (BA)'
  sr_cs: 'Serbian (RS/ME)'
  sr_me: 'Serbian (ME)'
  sr_rs: 'Serbian (RS)'
  sv: 'Swedish'
  sv_se: 'Swedish (SE)'
  th: 'Thai'
  th_th: 'Thai (TH)'
  tr: 'Turkish'
  tr_tr: 'Turkish (TR)'
  uk: 'Ukrainian'
  uk_ua: 'Ukrainian (UA)'
  vi: 'Vietnamese'
  vi_vn: 'Vietnamese (VN)'
  zh: 'Chinese'
  zh_cn: 'Chinese (CN)'
  zh_hk: 'Chinese (HK)'
  zh_sg: 'Chinese (SG)'
  zh_tw: 'Chinese (TW)'

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
