plan_0:
  name: Free
  max_monthly_recordings: 500
  monthly_price: {
    GBP: 0,
    EUR: 0,
    USD: 0
  }

plan_1:
  name: Light
  max_monthly_recordings: 5000
  monthly_price: {
    GBP: 38,
    EUR: 45,
    USD: 50
  }

plan_2:
  name: Plus
  max_monthly_recordings: 25000
  monthly_price: {
    GBP: 120,
    EUR: 145,
    USD: 165
  }

plan_3:
  name: Business
  max_monthly_recordings: 50000
  monthly_price: {
    GBP: 205,
    EUR: 245,
    USD: 275
  }

plan_4:
  name: Premium
  max_monthly_recordings: 100000
  monthly_price: {
    GBP: 410,
    EUR: 495,
    USD: 560
  }

plan_5:
  name: Unlimited
  max_monthly_recordings: null
  monthly_price: null
