:concurrency: 5
:queues:
  - default

:scheduler:
  :schedule:
    data_retention_job:
      cron: '0 0 1 * * *' # Every day at 01:00AM
      class: DataRetentionJob

    user_cleanup_job:
      cron: '0 0 1 * * *' # Every day at 01:00AM
      class: UserCleanupJob

    new_feedback_job:
      cron: '0 0 * * * *' # Every hour
      class: NewFeedbackJob

    events_processing_job:
      cron: '0 */15 * * * *' # Every 15 minutes
      class: EventsProcessingJob
