# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Feedback::NpsResponseFilters`.
# Please instead update this file by running `bin/tapioca dsl Types::Feedback::NpsResponseFilters`.

class Types::Feedback::NpsResponseFilters
  sig { returns(T.nilable(T::Boolean)) }
  def follow_up_comment; end

  sig { returns(T.nilable(::String)) }
  def outcome_type; end
end
