# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Feedback::SentimentResponseFilters`.
# Please instead update this file by running `bin/tapioca dsl Types::Feedback::SentimentResponseFilters`.

class Types::Feedback::SentimentResponseFilters
  sig { returns(T.nilable(T::Boolean)) }
  def follow_up_comment; end

  sig { returns(T.nilable(::Integer)) }
  def rating; end
end
