# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Common::FiltersDate`.
# Please instead update this file by running `bin/tapioca dsl Types::Common::FiltersDate`.

class Types::Common::FiltersDate
  sig { returns(T.nilable(::Date)) }
  def from_date; end

  sig { returns(T.nilable(::Date)) }
  def to_date; end
end
