# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `Types::Common::FiltersRecordings`.
# Please instead update this file by running `bin/tapioca dsl Types::Common::FiltersRecordings`.

class Types::Common::FiltersRecordings
  sig { returns(T.nilable(::Integer)) }
  def count; end

  sig { returns(T.nilable(::String)) }
  def range_type; end
end
